### ISSUE TITLE
watchTransition is not a function

### ISSUE THREAD

**Issue by mvanio** [novus/nvd3#1219]
While creating a multiBarHorizontalChart I stumbled across this issue...

    Uncaught TypeError: groups.exit(...).watchTransition is not a function
    (anonymous function) @ nv.d3.js:7166
    (anonymous function) @ d3.min.js:5
    H @ d3.min.js:1
    Hl.each @ d3.min.js:5
    chart @ nv.d3.js:7091
    ka.call @ d3.min.js:3
    (anonymous function) @ nv.d3.js:7620
    (anonymous function) @ d3.min.js:3
    H @ d3.min.js:1
    ka.each @ d3.min.js:3
    chart @ nv.d3.js:7500
    ka.call @ d3.min.js:3
    (anonymous function) @ pupil_data.js?01aa6aac26753071c816c9533f4dbaf6578db244:96
    (anonymous function) @ nv.d3.js:94

The data I have is very straightforward and follows the example here: http://nvd3.org/examples/multiBarHorizontalData.json. There are no transitions required. I called the chart with this;

      nv.addGraph(function() {
        chart_reading = nv.models.multiBarHorizontalChart()
          .x(function(d) { return d.label })
          .y(function(d) { return d.value })
          .margin({left: 100})
          .showValues(true)
          .showControls(false)
          .stacked(false)
          //.groupSpacing(0.2)
          ;

        chart_reading.yAxis.tickFormat(d3.format(',.2f'));

        d3.select('#charts svg')
          .datum(testPupil)
          .call(chart_reading)
        ;

And the error only occurs when the .call() function is called. I'm using Chrome 44.0.2403.157, Meteor 1.1.0.2.
Cheers!

**Comment by mvanio** [comment]
Have resolved by downgrading to nvd3:nvd3@=1.7.1, and d3js:d3@3.5.3. Works with Meteor 1.1.0.2 except for issues with bar colors and svg size set in nvd3-svg css class.

**Comment by DenJohX** [comment]
I was getting the same error. It happens that I was including asynchronously the d3 and nvd3 scripts, but is mandatory to load d3 before nvd3. As nvd3 redefines this function over the d3 selections.

**Comment by jstrachan** [comment]
@DenJohX many thanks - I hit this issue and your comment fixed it for me too; saved me lots of yak shaving!

**Comment by jaukia** [comment]
Thanks, had a similar issue when loading asynchronously scripts that were already loaded.

**Comment by dragondgold** [comment]
Hi! I'm having the same issue using [angular-nvd3](https://github.com/krispo/angular-nvd3). The error I'm getting is:

```
TypeError: groups.exit(...).watchTransition is not a function
    at SVGGElement.<anonymous> (http://localhost:1624/app/scripts/plugins/nv.d3.js:3950:18)
```

I'm using the latest `d3.js` version and the latest `nvd3` version. I'm including `d3.js` before `nv.d3.js` is this enough? Or how do I make sure `d3.js` is loaded before `nv.d3.js`?

**Comment by dragondgold** [comment]
Trying on simple webpage (no Angular) I'm also getting the error `pieLabels.watchTransition is not a function` when trying [this](https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/pieChart.html) example. The first chart (the left one) is rendered but the other is not.

**Comment by siva3378** [comment]
@dragondgold Even I'm facing the same issue with angular#1.4.2 jquery#2.1.4 d3#3.5.3 nvd3#1.7.1 & angular-nvd3#1.0.5

**Comment by dragondgold** [comment]
@siva3378 You are working with Node.js right? How do you inject d3 as a constant in Angular? What do you mean?

**Comment by siva3378** [comment]
@dragondgold Yes, I'm working with Node.js. Basically, when we load our webpage in a browser d3 will be our global object. 

we can register d3 as a constant in our angular module as 
`angular.module('your-module').constant('d3', d3);`

In your controller or service where ever you use d3, you can inject into your function as
`angular.module('your-module').controller('DashboardController', function($scope, d3){
        // you can use d3 object here
});`

**Comment by sumittops** [comment]
@siva3378 - Thanks a lot. I also faced similar issues. angular.module('your-module').constant('d3', d3); did the job for me. 👍

**Comment by vcernomschi** [comment]
@DenJohX  - Thanks. I also encountered with this issue and your comment helped me too.

**Comment by naveenjafer** [comment]
return $ocLazyLoad.load(
                {
                    name:'sbAdminApp',
                    files:[
                    'scripts/directives/header/header.js',
                    'scripts/directives/header/header-notification/header-notification.js',
                    'scripts/directives/sidebar/sidebar.js',
                    'scripts/directives/sidebar/sidebar-search/sidebar-search.js',
                    'bower_components/d3/d3.js',
                      'bower_components/nvd3/build/nv.d3.js',
                      'bower_components/nvd3/build/nv.d3.css',
                      'bower_components/angular-nvd3/dist/angular-nvd3.js'
                    ]
                }),

How do I fix this error in this case? The error is pretty erratic. It is more or less an on/off thing happening occasionally.

**Comment by DenJohX** [comment]
@naveenjafer I don't use Angular anymore, but there should be some way for ocLazyLoad to inject the files in the right order, maybe doing it synchronously or ensuring d3 loads before the files array.

**Comment by naveenjafer** [comment]
Thank you,
   Got if fixed using the serie option.

Warm regards
Naveen Jafer

**Comment by njbuch** [comment]
Ping! Still seeing this error in the 1.8.4 version!

**Comment by znoland3** [comment]
I got around this bug by extracting and referencing the D3 and NVD3 files used on their site for the examples. Zipped files below.

[nv.d3.zip](https://github.com/novus/nvd3/files/460527/nv.d3.zip)

**Comment by PascalLaier** [comment]
UP This is still happening

**Comment by mujtaba27** [comment]
> I was getting the same error. It happens that I was including asynchronously the d3 and nvd3 scripts, but is mandatory to load d3 before nvd3. As nvd3 redefines this function over the d3 selections.

@DenJohX  can you guide me how to load d3 before nvd3. im using angular 6. thnx

**Comment by Tahirhan** [comment]
i faced with same issue, it was beacuse i forget to add nvd3 css and js libs into code. it solved after adding libs. (Don't forget to add libs after d3.v3 lib)
